version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/workspace:cached
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    ports:
      - "22111:8000"